/*----- PROTECTED REGION ID(SlsDetectorClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        SlsDetectorClass.h
//
// description : Include for the SlsDetector root class.
//               This class is the singleton class for
//                the SlsDetector device class.
//               It contains all properties and methods which the 
//               SlsDetector requires only once e.g. the commands.
//
// project :     Sls dectector TANGO specific device.
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef SlsDetectorClass_H
#define SlsDetectorClass_H

#include <tango.h>
#include <SlsDetector.h>


/*----- PROTECTED REGION END -----*/	//	SlsDetectorClass.h


namespace SlsDetector_ns
{
/*----- PROTECTED REGION ID(SlsDetectorClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	SlsDetectorClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute tresholdEnergy class definition
class tresholdEnergyAttrib: public Tango::Attr
{
public:
	tresholdEnergyAttrib():Attr("tresholdEnergy",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~tresholdEnergyAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetector *>(dev))->read_tresholdEnergy(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetector *>(dev))->write_tresholdEnergy(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetector *>(dev))->is_tresholdEnergy_allowed(ty);}
};

//	Attribute clockDivider class definition
class clockDividerAttrib: public Tango::Attr
{
public:
	clockDividerAttrib():Attr("clockDivider",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~clockDividerAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetector *>(dev))->read_clockDivider(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetector *>(dev))->write_clockDivider(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetector *>(dev))->is_clockDivider_allowed(ty);}
};


/**
 *	The SlsDetectorClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  SlsDetectorClass : public Tango::DeviceClass
#else
class SlsDetectorClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(SlsDetectorClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static SlsDetectorClass *init(const char *);
		static SlsDetectorClass *instance();
		~SlsDetectorClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		SlsDetectorClass(string &);
		static SlsDetectorClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	SlsDetector_H
